source "https://rubygems.org"

gem "elixir-toolkit-theme-plugins", "~> 1.1"
gem "webrick", "~> 1.9"
gem "jekyll", "~> 4.4"
gem "jemoji", "~> 0.13"
gem "kramdown-parser-gfm", "~> 1.1"
gem "csv", "~> 3.3"
gem "faraday-retry", "~> 2.4"

group :jekyll_plugins do
  gem "jekyll-redirect-from", "~> 0.16.0"
  gem "jekyll-sitemap", "~> 1.4"
  gem "jekyll-github-metadata", "~> 2.16"
  gem "jekyll-relative-links", "~> 0.8"
  gem "jekyll-seo-tag", "~> 2.9"
  gem "jekyll-remote-theme", "~> 0.5"
end
